### ISSUE TITLE
[Bug]: tests/apps/dial/preserve_top keeps failing

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/testsuite#60]
### Severity

Trivial

### Versions

all

### Components/Modules

tests/apps/dial/preserve_top

### Operating Environment

rocky8

### Frequency of Occurrence

Frequent

### Issue Description

@maximilianfridrich Can you take a look at this test?  It appears that the middle (I think) sipp scenario fails on a regular basis.  It's most probably timing related so if you're going to test locally, I'd suggest doing it in a resource-constrained docker container.  

I'm attaching the logs from the last run.

[Nightly-apps_funcs-18.zip](https://github.com/user-attachments/files/16442571/Nightly-apps_funcs-18.zip)

### Relevant log output

```shell
Running tests/apps/dial/preserve_top ...
[Jul 31 02:28:57] WARNING[18493]: asterisk.sipp:572 processEnded: b"Resolving remote host '127.0.0.1'... Done.n"
[Jul 31 02:28:57] WARNING[18493]: asterisk.sipp:572 processEnded: b"2024-07-31t02:28:51.314321t1722392931.314321: Failed regexp match: looking in 'v=0rno=- 911699183 911699183 IN IP4 127.0.0.1rns=Asteriskrnc=IN IP4 127.0.0.1rnt=0 0rnm=audio 16940 RTP/AVP 9 0 8 101rna=rtpmap:9 G722/8000rna=rtpmap:0 PCMU/8000rna=rtpmap:8 PCMA/8000rna=rtpmap:101 telephone-event/8000rna=fmtp:101 0-16rna=ptime:20rna=maxptime:140rna=sendrecvrnm=video 15046 RTP/AVP 99 34rna=rtpmap:99 H264/90000rna=rtpmap:34 H263/90000rna=fmtprna=sendrecvrn', with regexp 'a=sendonly'n"
[Jul 31 02:28:57] WARNING[18493]: asterisk.sipp:675 __scenario_callback: SIPp Scenario carol2.xml Failed [1]
[Jul 31 02:28:57] WARNING[18493]: asterisk.sipp:231 _handle_scenario_finished: Scenario carol2.xml failed
[Jul 31 02:28:57] WARNING[18493]: asterisk.sipp:473 __execute_next: SIPp Scenario carol2.xml Failed
Test tests/apps/dial/preserve_top failed
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by maximilianfridrich** [comment]
I will look into it.
